version: '2'

services:
  kafka1:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1 //宿主机ip
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
    volumes:
    - /e/cluster/kafka/kafka1/logs:/kafka
    external_links:
    - zookeeper1
    - zookeeper2
    - zookeeper3
    networks:
      default:
        ipv4_address: 172.19.0.14

  kafka2:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
    - 9093:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2 //宿主机IP
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
    volumes:
    - /e/cluster/kafka/kafka2/logs:/kafka
    external_links:
    - zookeeper1
    - zookeeper2
    - zookeeper3
    networks:
      default:
        ipv4_address: 172.19.0.15

  kafka3:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
    - 9094:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3 //宿主机IP
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
    volumes:
    - /e/cluster/kafka/kafka3/logs:/kafka
    external_links:
    - zookeeper1
    - zookeeper2
    - zookeeper3
    networks:
      default:
        ipv4_address: 172.19.0.16

networks:
  default:
    external:
      name: zookeeper_network
